package bo.jads.myfinancesbackend.app.domain.entities.enums;

public enum ActionCode {

    NONE,
    USER_REGISTRATION,
    USER_UPDATE,
    LOGIN,
    PASSWORD_RESET,
    ACCOUNT_CREATION,
    ACCOUNT_UPDATE,
    ACCOUNT_DELETION,
    USER_TO_ACCOUNT_ASSOCIATION,
    USER_ACCOUNT_DEACTIVATION,
    MOVEMENT_REGISTRATION,
    MOVEMENT_UPDATE,
    MOVEMENT_DELETION

}
