/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 03-jun.-2023 22:31:29 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS `users`;

DROP TABLE IF EXISTS `currencies`;

DROP TABLE IF EXISTS `actions`;

DROP TABLE IF EXISTS `activity_logs`;

DROP TABLE IF EXISTS `accounts`;

DROP TABLE IF EXISTS `user_accounts`;

DROP TABLE IF EXISTS `movement_categories`;

DROP TABLE IF EXISTS `movements`;

DROP TABLE IF EXISTS `movement_templates`;

DROP TABLE IF EXISTS `movement_details`;

DROP TABLE IF EXISTS `confirmed_movements`;

DROP TABLE IF EXISTS `account_actions`;

DROP TABLE IF EXISTS `user_account_actions`;

/* Create Tables */

CREATE TABLE `users`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(64) NOT NULL UNIQUE,
	`password` VARCHAR(512) NOT NULL,
	`code` VARCHAR(64) NOT NULL,
	`status` VARCHAR(64) NOT NULL,
	`names` VARCHAR(128) NOT NULL,
	`first_surname` VARCHAR(128) NULL,
	`second_surname` VARCHAR(128) NULL,
	`email` VARCHAR(320) NOT NULL UNIQUE,
	`phone` VARCHAR(64) NULL,
	`photo_path` VARCHAR(512) NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `currencies`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL,
	`code` VARCHAR(16) NOT NULL,
	`symbol` VARCHAR(16) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `actions`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL,
	`code` VARCHAR(64) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `activity_logs`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`execution_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`result` VARCHAR(16) NOT NULL,
	`message` VARCHAR(512) NOT NULL,
	`affected_entity_id` BIGINT NOT NULL,
	`affected_entity_type` VARCHAR(32) NOT NULL,
	`user_id` BIGINT NOT NULL,
	`action_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),
	FOREIGN KEY (`action_id`) REFERENCES `actions`(`id`)
);

CREATE TABLE `accounts`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL,
	`description` VARCHAR(128) NULL,
	`initial_balance` DECIMAL(10,6) NOT NULL,
	`total_income` DECIMAL(10,6) NOT NULL,
	`total_expense` DECIMAL(10,6) NOT NULL,
	`current_balance` DECIMAL(10,6) NOT NULL,
	`icon` VARCHAR(64) NULL,
	`deleted` BIT NOT NULL DEFAULT FALSE,
	`currency_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`currency_id`) REFERENCES `currencies`(`id`)
);

CREATE TABLE `user_accounts`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`active` BIT NOT NULL DEFAULT TRUE,
	`user_id` BIGINT NOT NULL,
	`account_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`)
);

CREATE TABLE `movement_categories`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL,
	`is_income` BIT NOT NULL,
	`icon` VARCHAR(64) NULL,
	`deleted` BIT NOT NULL DEFAULT FALSE,
	`account_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`)
);

CREATE TABLE `movements`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`total_amount` DECIMAL(10,6) NOT NULL,
	`description` VARCHAR(512) NULL,
	`photo` VARCHAR(512) NULL,
	`deleted` BIT NOT NULL DEFAULT FALSE,
	`movement_category_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`movement_category_id`) REFERENCES `movement_categories`(`id`)
);

CREATE TABLE `movement_templates`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`movement_id` BIGINT NOT NULL,
	`account_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`movement_id`) REFERENCES `movements`(`id`),
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`)
);

CREATE TABLE `movement_details`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(512) NULL,
	`amount` DECIMAL(10,6) NOT NULL,
	`movement_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`movement_id`) REFERENCES `movements`(`id`)
);

CREATE TABLE `confirmed_movements`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`registration_timestamp` TIMESTAMP NOT NULL,
	`movement_id` BIGINT NOT NULL,
	`user_account_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`movement_id`) REFERENCES `movements`(`id`),
	FOREIGN KEY (`user_account_id`) REFERENCES `user_accounts`(`id`)
);

CREATE TABLE `account_actions`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`action_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`action_id`) REFERENCES `actions`(`id`)
);

CREATE TABLE `user_account_actions`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`deleted` BIT NOT NULL DEFAULT FALSE,
	`user_account_id` BIGINT NOT NULL,
	`account_action_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`user_account_id`) REFERENCES `user_accounts`(`id`),
	FOREIGN KEY (`account_action_id`) REFERENCES `account_actions`(`id`)
);

SET FOREIGN_KEY_CHECKS=1;
